### ISSUE TITLE
rate limit exceeded

### ISSUE THREAD

**Issue by shadoxxhd** [sidoh/reactor_simulator#4]
what does this mean?

**Comment by sidoh** [comment]
I have a request rate limit configured at the endpoint. My server was getting hit pretty hard at some point and it turned out to be because a couple of people were spamming the "simulate" button. I implemented this shortly afterwards to prevent that sort of thing from happening.

The limit is pretty liberal. It's something like 30 requests / minute. I increased the "burst" amount to 30 from 10, so it should show up less. Let me know if it's a problem.

**Comment by shadoxxhd** [comment]
its a bit confusing if you add blocks one by one in fast succession, and suddenly this shows up. thought it would be some kind of hidden reactor value :D

to prevent this, you could just limit the auto-updates on changes to 1 per 2 seconds, since the message somewhat encourages simulate spamming if you dont know why the simulation failed
